services:
  web:
    build: .
    container_name: vagos_software_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && next dev"
